// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrj4Q5lu0hXVCut3v8UDuGItPKH99KoA4',
    appId: '1:931836881753:web:ef63ac3fa68b3d74ebba48',
    messagingSenderId: '931836881753',
    projectId: 'fooddilveryapp-30d35',
    authDomain: 'fooddilveryapp-30d35.firebaseapp.com',
    storageBucket: 'fooddilveryapp-30d35.appspot.com',
    measurementId: 'G-J1BL2TQDGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuBX6CkN0tncI9VqM2H3FgdUqiXGqvS7A',
    appId: '1:931836881753:android:982cc2930adef499ebba48',
    messagingSenderId: '931836881753',
    projectId: 'fooddilveryapp-30d35',
    storageBucket: 'fooddilveryapp-30d35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoyCbaj-0XQWxuW4TAAQ4Xjjf_pQRseqs',
    appId: '1:931836881753:ios:835cfd5f3384ba85ebba48',
    messagingSenderId: '931836881753',
    projectId: 'fooddilveryapp-30d35',
    storageBucket: 'fooddilveryapp-30d35.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoyCbaj-0XQWxuW4TAAQ4Xjjf_pQRseqs',
    appId: '1:931836881753:ios:835cfd5f3384ba85ebba48',
    messagingSenderId: '931836881753',
    projectId: 'fooddilveryapp-30d35',
    storageBucket: 'fooddilveryapp-30d35.appspot.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrj4Q5lu0hXVCut3v8UDuGItPKH99KoA4',
    appId: '1:931836881753:web:06916fda4d19cca6ebba48',
    messagingSenderId: '931836881753',
    projectId: 'fooddilveryapp-30d35',
    authDomain: 'fooddilveryapp-30d35.firebaseapp.com',
    storageBucket: 'fooddilveryapp-30d35.appspot.com',
    measurementId: 'G-D3SJLM10MJ',
  );
}
